name: Simple E2E Workflow - DEV Env

on:
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "Ejecutando trabajo en entorno DEV: $MY_VARIABLE AND $GH_TOKEN"
        env:
          MY_VARIABLE: ${{ vars.MY_VARIABLE }}
          GH_TOKEN: ${{ secrets.CUSTOMTOKEN }}